version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:80"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis
      - db
    env_file:
      - ./.env
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=<your_password>
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: