version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"